# Generated by Django 3.0.7 on 2020-06-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0002_auto_20200620_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='img',
            field=models.ImageField(upload_to='media/writings'),
        ),
    ]
