# Generated by Django 3.0.7 on 2020-06-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0003_auto_20200621_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='img',
            field=models.ImageField(upload_to='writings/'),
        ),
    ]
