# Generated by Django 3.0.7 on 2020-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writings', '0004_auto_20200621_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='img',
            field=models.ImageField(blank=True, upload_to='writings/'),
        ),
    ]
