# Generated by Django 3.0.7 on 2020-07-02 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writings', '0005_auto_20200621_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='WComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='writings.WComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writings.Writing')),
            ],
        ),
    ]
