# Generated by Django 3.0.7 on 2020-06-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200620_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
