# Generated by Django 3.0.7 on 2020-07-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200702_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='views',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
