# Generated by Django 3.0.7 on 2020-07-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_tech_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
